name: 'dbt_bigquery_ecommerce'
version: '1.0.0'
config-version: 2

profile: 'dbt_bigquery_ecommerce'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_bigquery_ecommerce:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: ephemeral
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts

snapshots:
  dbt_bigquery_ecommerce:
    +schema: snapshots

vars:
  thelook_project: 'bigquery-public-data'
  thelook_dataset: 'thelook_ecommerce'
#  snapshot_schema: 'dbt_t14_dev_snapshots'
